/*
 * eSignAnywhere.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package osplus.esignanywhere.v4.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Configure the adhoc workstep creation.
 */
@ApiModel(description = "Configure the adhoc workstep creation.")
@JsonPropertyOrder({
  AdHocWorkstepConfiguration.JSON_PROPERTY_WORKSTEP_LABEL,
  AdHocWorkstepConfiguration.JSON_PROPERTY_SMALL_TEXT_ZOOM_FACTOR_PERCENT,
  AdHocWorkstepConfiguration.JSON_PROPERTY_WORKSTEP_TIME_TO_LIVE_IN_MINUTES,
  AdHocWorkstepConfiguration.JSON_PROPERTY_FINISH_ACTION,
  AdHocWorkstepConfiguration.JSON_PROPERTY_NO_SEQUENCE_ENFORCED,
  AdHocWorkstepConfiguration.JSON_PROPERTY_SIG_TEMPLATE,
  AdHocWorkstepConfiguration.JSON_PROPERTY_PARSE_FORM_FIELDS,
  AdHocWorkstepConfiguration.JSON_PROPERTY_ADHOC_POLICIES,
  AdHocWorkstepConfiguration.JSON_PROPERTY_VIEWER_PREFERENCES,
  AdHocWorkstepConfiguration.JSON_PROPERTY_SIGNATURE_CONFIGURATIONS,
  AdHocWorkstepConfiguration.JSON_PROPERTY_SIG_STRING_PARSING_CONFIGURATION,
  AdHocWorkstepConfiguration.JSON_PROPERTY_GENERAL_POLICIES,
  AdHocWorkstepConfiguration.JSON_PROPERTY_FINALIZE_ACTIONS,
  AdHocWorkstepConfiguration.JSON_PROPERTY_TRANSACTION_CODE_CONFIGURATIONS
})
@JsonTypeName("AdHocWorkstepConfiguration")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T11:25:21.496783+01:00[Europe/Berlin]")
public class AdHocWorkstepConfiguration {
  public static final String JSON_PROPERTY_WORKSTEP_LABEL = "WorkstepLabel";
  private String workstepLabel = "";

  public static final String JSON_PROPERTY_SMALL_TEXT_ZOOM_FACTOR_PERCENT = "SmallTextZoomFactorPercent";
  private Integer smallTextZoomFactorPercent = 100;

  public static final String JSON_PROPERTY_WORKSTEP_TIME_TO_LIVE_IN_MINUTES = "WorkstepTimeToLiveInMinutes";
  private Integer workstepTimeToLiveInMinutes = 43200;

  public static final String JSON_PROPERTY_FINISH_ACTION = "FinishAction";
  private FinishAction finishAction;

  public static final String JSON_PROPERTY_NO_SEQUENCE_ENFORCED = "NoSequenceEnforced";
  private Boolean noSequenceEnforced = true;

  public static final String JSON_PROPERTY_SIG_TEMPLATE = "SigTemplate";
  private SigTemplate sigTemplate;

  public static final String JSON_PROPERTY_PARSE_FORM_FIELDS = "ParseFormFields";
  private ParseFormFields parseFormFields;

  public static final String JSON_PROPERTY_ADHOC_POLICIES = "AdhocPolicies";
  private AdhocPolicies adhocPolicies;

  public static final String JSON_PROPERTY_VIEWER_PREFERENCES = "ViewerPreferences";
  private ViewerPreferences viewerPreferences;

  public static final String JSON_PROPERTY_SIGNATURE_CONFIGURATIONS = "SignatureConfigurations";
  private List<SignatureConfiguration> signatureConfigurations = null;

  public static final String JSON_PROPERTY_SIG_STRING_PARSING_CONFIGURATION = "SigStringParsingConfiguration";
  private SigStringParsingConfiguration sigStringParsingConfiguration;

  public static final String JSON_PROPERTY_GENERAL_POLICIES = "GeneralPolicies";
  private GeneralPolicies generalPolicies;

  public static final String JSON_PROPERTY_FINALIZE_ACTIONS = "FinalizeActions";
  private FinalizeActions finalizeActions;

  public static final String JSON_PROPERTY_TRANSACTION_CODE_CONFIGURATIONS = "TransactionCodeConfigurations";
  private List<TransactionCodeConfiguration> transactionCodeConfigurations = null;


  public AdHocWorkstepConfiguration workstepLabel(String workstepLabel) {
    
    this.workstepLabel = workstepLabel;
    return this;
  }

   /**
   * A label for this workstep
   * @return workstepLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A label for this workstep")
  @JsonProperty(JSON_PROPERTY_WORKSTEP_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWorkstepLabel() {
    return workstepLabel;
  }


  public void setWorkstepLabel(String workstepLabel) {
    this.workstepLabel = workstepLabel;
  }


  public AdHocWorkstepConfiguration smallTextZoomFactorPercent(Integer smallTextZoomFactorPercent) {
    
    this.smallTextZoomFactorPercent = smallTextZoomFactorPercent;
    return this;
  }

   /**
   * Defines a image generation correction factor. If for example this document contains very small text, which might not be readable with the standard image resolution of the client, this factor can be used to tell the client to get a higher resolution.
   * @return smallTextZoomFactorPercent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Defines a image generation correction factor. If for example this document contains very small text, which might not be readable with the standard image resolution of the client, this factor can be used to tell the client to get a higher resolution.")
  @JsonProperty(JSON_PROPERTY_SMALL_TEXT_ZOOM_FACTOR_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSmallTextZoomFactorPercent() {
    return smallTextZoomFactorPercent;
  }


  public void setSmallTextZoomFactorPercent(Integer smallTextZoomFactorPercent) {
    this.smallTextZoomFactorPercent = smallTextZoomFactorPercent;
  }


  public AdHocWorkstepConfiguration workstepTimeToLiveInMinutes(Integer workstepTimeToLiveInMinutes) {
    
    this.workstepTimeToLiveInMinutes = workstepTimeToLiveInMinutes;
    return this;
  }

   /**
   * Defines the time to live of all the documents created by the workstep. After this time to live is expired, all documents are deleted. &#39;0&#39; sets the time to live to forever.
   * @return workstepTimeToLiveInMinutes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Defines the time to live of all the documents created by the workstep. After this time to live is expired, all documents are deleted. '0' sets the time to live to forever.")
  @JsonProperty(JSON_PROPERTY_WORKSTEP_TIME_TO_LIVE_IN_MINUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWorkstepTimeToLiveInMinutes() {
    return workstepTimeToLiveInMinutes;
  }


  public void setWorkstepTimeToLiveInMinutes(Integer workstepTimeToLiveInMinutes) {
    this.workstepTimeToLiveInMinutes = workstepTimeToLiveInMinutes;
  }


  public AdHocWorkstepConfiguration finishAction(FinishAction finishAction) {
    
    this.finishAction = finishAction;
    return this;
  }

   /**
   * Get finishAction
   * @return finishAction
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FINISH_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FinishAction getFinishAction() {
    return finishAction;
  }


  public void setFinishAction(FinishAction finishAction) {
    this.finishAction = finishAction;
  }


  public AdHocWorkstepConfiguration noSequenceEnforced(Boolean noSequenceEnforced) {
    
    this.noSequenceEnforced = noSequenceEnforced;
    return this;
  }

   /**
   * Define the sequence mode.
   * @return noSequenceEnforced
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Define the sequence mode.")
  @JsonProperty(JSON_PROPERTY_NO_SEQUENCE_ENFORCED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNoSequenceEnforced() {
    return noSequenceEnforced;
  }


  public void setNoSequenceEnforced(Boolean noSequenceEnforced) {
    this.noSequenceEnforced = noSequenceEnforced;
  }


  public AdHocWorkstepConfiguration sigTemplate(SigTemplate sigTemplate) {
    
    this.sigTemplate = sigTemplate;
    return this;
  }

   /**
   * Get sigTemplate
   * @return sigTemplate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIG_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SigTemplate getSigTemplate() {
    return sigTemplate;
  }


  public void setSigTemplate(SigTemplate sigTemplate) {
    this.sigTemplate = sigTemplate;
  }


  public AdHocWorkstepConfiguration parseFormFields(ParseFormFields parseFormFields) {
    
    this.parseFormFields = parseFormFields;
    return this;
  }

   /**
   * Get parseFormFields
   * @return parseFormFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARSE_FORM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ParseFormFields getParseFormFields() {
    return parseFormFields;
  }


  public void setParseFormFields(ParseFormFields parseFormFields) {
    this.parseFormFields = parseFormFields;
  }


  public AdHocWorkstepConfiguration adhocPolicies(AdhocPolicies adhocPolicies) {
    
    this.adhocPolicies = adhocPolicies;
    return this;
  }

   /**
   * Get adhocPolicies
   * @return adhocPolicies
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADHOC_POLICIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AdhocPolicies getAdhocPolicies() {
    return adhocPolicies;
  }


  public void setAdhocPolicies(AdhocPolicies adhocPolicies) {
    this.adhocPolicies = adhocPolicies;
  }


  public AdHocWorkstepConfiguration viewerPreferences(ViewerPreferences viewerPreferences) {
    
    this.viewerPreferences = viewerPreferences;
    return this;
  }

   /**
   * Get viewerPreferences
   * @return viewerPreferences
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VIEWER_PREFERENCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ViewerPreferences getViewerPreferences() {
    return viewerPreferences;
  }


  public void setViewerPreferences(ViewerPreferences viewerPreferences) {
    this.viewerPreferences = viewerPreferences;
  }


  public AdHocWorkstepConfiguration signatureConfigurations(List<SignatureConfiguration> signatureConfigurations) {
    
    this.signatureConfigurations = signatureConfigurations;
    return this;
  }

  public AdHocWorkstepConfiguration addSignatureConfigurationsItem(SignatureConfiguration signatureConfigurationsItem) {
    if (this.signatureConfigurations == null) {
      this.signatureConfigurations = new ArrayList<SignatureConfiguration>();
    }
    this.signatureConfigurations.add(signatureConfigurationsItem);
    return this;
  }

   /**
   * Configurate the signatures for this workstep. One default configuration has to be defined. The default configuration is used for flatten signatures, adhoc signatures and signature fields which do not reference a special signature plugin configuration. The default configuration does not contain the attribute &#39;spcId&#39;. If the attribute &#39;spcId&#39; is defined the signature plugin configuration does only apply to signature fields referencing the configuration by specifiying &lt;param name&#x3D;\&quot;spcId\&quot;&gt;id&lt;/param&gt;.
   * @return signatureConfigurations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Configurate the signatures for this workstep. One default configuration has to be defined. The default configuration is used for flatten signatures, adhoc signatures and signature fields which do not reference a special signature plugin configuration. The default configuration does not contain the attribute 'spcId'. If the attribute 'spcId' is defined the signature plugin configuration does only apply to signature fields referencing the configuration by specifiying <param name=\"spcId\">id</param>.")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_CONFIGURATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SignatureConfiguration> getSignatureConfigurations() {
    return signatureConfigurations;
  }


  public void setSignatureConfigurations(List<SignatureConfiguration> signatureConfigurations) {
    this.signatureConfigurations = signatureConfigurations;
  }


  public AdHocWorkstepConfiguration sigStringParsingConfiguration(SigStringParsingConfiguration sigStringParsingConfiguration) {
    
    this.sigStringParsingConfiguration = sigStringParsingConfiguration;
    return this;
  }

   /**
   * Get sigStringParsingConfiguration
   * @return sigStringParsingConfiguration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIG_STRING_PARSING_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SigStringParsingConfiguration getSigStringParsingConfiguration() {
    return sigStringParsingConfiguration;
  }


  public void setSigStringParsingConfiguration(SigStringParsingConfiguration sigStringParsingConfiguration) {
    this.sigStringParsingConfiguration = sigStringParsingConfiguration;
  }


  public AdHocWorkstepConfiguration generalPolicies(GeneralPolicies generalPolicies) {
    
    this.generalPolicies = generalPolicies;
    return this;
  }

   /**
   * Get generalPolicies
   * @return generalPolicies
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GENERAL_POLICIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GeneralPolicies getGeneralPolicies() {
    return generalPolicies;
  }


  public void setGeneralPolicies(GeneralPolicies generalPolicies) {
    this.generalPolicies = generalPolicies;
  }


  public AdHocWorkstepConfiguration finalizeActions(FinalizeActions finalizeActions) {
    
    this.finalizeActions = finalizeActions;
    return this;
  }

   /**
   * Get finalizeActions
   * @return finalizeActions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FINALIZE_ACTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FinalizeActions getFinalizeActions() {
    return finalizeActions;
  }


  public void setFinalizeActions(FinalizeActions finalizeActions) {
    this.finalizeActions = finalizeActions;
  }


  public AdHocWorkstepConfiguration transactionCodeConfigurations(List<TransactionCodeConfiguration> transactionCodeConfigurations) {
    
    this.transactionCodeConfigurations = transactionCodeConfigurations;
    return this;
  }

  public AdHocWorkstepConfiguration addTransactionCodeConfigurationsItem(TransactionCodeConfiguration transactionCodeConfigurationsItem) {
    if (this.transactionCodeConfigurations == null) {
      this.transactionCodeConfigurations = new ArrayList<TransactionCodeConfiguration>();
    }
    this.transactionCodeConfigurations.add(transactionCodeConfigurationsItem);
    return this;
  }

   /**
   * Collection of TransactionCodeConfigurations
   * @return transactionCodeConfigurations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Collection of TransactionCodeConfigurations")
  @JsonProperty(JSON_PROPERTY_TRANSACTION_CODE_CONFIGURATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TransactionCodeConfiguration> getTransactionCodeConfigurations() {
    return transactionCodeConfigurations;
  }


  public void setTransactionCodeConfigurations(List<TransactionCodeConfiguration> transactionCodeConfigurations) {
    this.transactionCodeConfigurations = transactionCodeConfigurations;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdHocWorkstepConfiguration adHocWorkstepConfiguration = (AdHocWorkstepConfiguration) o;
    return Objects.equals(this.workstepLabel, adHocWorkstepConfiguration.workstepLabel) &&
        Objects.equals(this.smallTextZoomFactorPercent, adHocWorkstepConfiguration.smallTextZoomFactorPercent) &&
        Objects.equals(this.workstepTimeToLiveInMinutes, adHocWorkstepConfiguration.workstepTimeToLiveInMinutes) &&
        Objects.equals(this.finishAction, adHocWorkstepConfiguration.finishAction) &&
        Objects.equals(this.noSequenceEnforced, adHocWorkstepConfiguration.noSequenceEnforced) &&
        Objects.equals(this.sigTemplate, adHocWorkstepConfiguration.sigTemplate) &&
        Objects.equals(this.parseFormFields, adHocWorkstepConfiguration.parseFormFields) &&
        Objects.equals(this.adhocPolicies, adHocWorkstepConfiguration.adhocPolicies) &&
        Objects.equals(this.viewerPreferences, adHocWorkstepConfiguration.viewerPreferences) &&
        Objects.equals(this.signatureConfigurations, adHocWorkstepConfiguration.signatureConfigurations) &&
        Objects.equals(this.sigStringParsingConfiguration, adHocWorkstepConfiguration.sigStringParsingConfiguration) &&
        Objects.equals(this.generalPolicies, adHocWorkstepConfiguration.generalPolicies) &&
        Objects.equals(this.finalizeActions, adHocWorkstepConfiguration.finalizeActions) &&
        Objects.equals(this.transactionCodeConfigurations, adHocWorkstepConfiguration.transactionCodeConfigurations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workstepLabel, smallTextZoomFactorPercent, workstepTimeToLiveInMinutes, finishAction, noSequenceEnforced, sigTemplate, parseFormFields, adhocPolicies, viewerPreferences, signatureConfigurations, sigStringParsingConfiguration, generalPolicies, finalizeActions, transactionCodeConfigurations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdHocWorkstepConfiguration {\n");
    sb.append("    workstepLabel: ").append(toIndentedString(workstepLabel)).append("\n");
    sb.append("    smallTextZoomFactorPercent: ").append(toIndentedString(smallTextZoomFactorPercent)).append("\n");
    sb.append("    workstepTimeToLiveInMinutes: ").append(toIndentedString(workstepTimeToLiveInMinutes)).append("\n");
    sb.append("    finishAction: ").append(toIndentedString(finishAction)).append("\n");
    sb.append("    noSequenceEnforced: ").append(toIndentedString(noSequenceEnforced)).append("\n");
    sb.append("    sigTemplate: ").append(toIndentedString(sigTemplate)).append("\n");
    sb.append("    parseFormFields: ").append(toIndentedString(parseFormFields)).append("\n");
    sb.append("    adhocPolicies: ").append(toIndentedString(adhocPolicies)).append("\n");
    sb.append("    viewerPreferences: ").append(toIndentedString(viewerPreferences)).append("\n");
    sb.append("    signatureConfigurations: ").append(toIndentedString(signatureConfigurations)).append("\n");
    sb.append("    sigStringParsingConfiguration: ").append(toIndentedString(sigStringParsingConfiguration)).append("\n");
    sb.append("    generalPolicies: ").append(toIndentedString(generalPolicies)).append("\n");
    sb.append("    finalizeActions: ").append(toIndentedString(finalizeActions)).append("\n");
    sb.append("    transactionCodeConfigurations: ").append(toIndentedString(transactionCodeConfigurations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

