/*
 * eSignAnywhere.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package osplus.esignanywhere.v4.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Item in a form list.
 */
@ApiModel(description = "Item in a form list.")
@JsonPropertyOrder({
  BoxItem.JSON_PROPERTY_KEY,
  BoxItem.JSON_PROPERTY_VALUE,
  BoxItem.JSON_PROPERTY_IS_SELECTED
})
@JsonTypeName("BoxItem")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-28T10:42:13.714738+01:00[Europe/Berlin]")
public class BoxItem {
  public static final String JSON_PROPERTY_KEY = "Key";
  private String key;

  public static final String JSON_PROPERTY_VALUE = "Value";
  private String value;

  public static final String JSON_PROPERTY_IS_SELECTED = "IsSelected";
  private Boolean isSelected;


  public BoxItem key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * Key of the item.
   * @return key
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Key of the item.")
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKey() {
    return key;
  }


  public void setKey(String key) {
    this.key = key;
  }


  public BoxItem value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Value of the item.
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Value of the item.")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


  public BoxItem isSelected(Boolean isSelected) {
    
    this.isSelected = isSelected;
    return this;
  }

   /**
   * Defines if the item is selected.
   * @return isSelected
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Defines if the item is selected.")
  @JsonProperty(JSON_PROPERTY_IS_SELECTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsSelected() {
    return isSelected;
  }


  public void setIsSelected(Boolean isSelected) {
    this.isSelected = isSelected;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoxItem boxItem = (BoxItem) o;
    return Objects.equals(this.key, boxItem.key) &&
        Objects.equals(this.value, boxItem.value) &&
        Objects.equals(this.isSelected, boxItem.isSelected);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, value, isSelected);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoxItem {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    isSelected: ").append(toIndentedString(isSelected)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

