/*
 * eSignAnywhere.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package osplus.esignanywhere.v4.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import io.swagger.annotations.ApiModelProperty;

/**
 * DraftCreateFromTemplateModel
 */
@JsonPropertyOrder({
  DraftCreateFromTemplateModel.JSON_PROPERTY_TEMPLATE_ID,
  DraftCreateFromTemplateModel.JSON_PROPERTY_ENVELOPE_OVERRIDE_OPTIONS,
  DraftCreateFromTemplateModel.JSON_PROPERTY_CREATE_DRAFT_OPTIONS
})
@JsonTypeName("DraftCreateFromTemplateModel")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-28T10:42:13.714738+01:00[Europe/Berlin]")
public class DraftCreateFromTemplateModel {
  public static final String JSON_PROPERTY_TEMPLATE_ID = "TemplateId";
  private String templateId;

  public static final String JSON_PROPERTY_ENVELOPE_OVERRIDE_OPTIONS = "EnvelopeOverrideOptions";
  private EnvelopeOverrideOptions envelopeOverrideOptions;

  public static final String JSON_PROPERTY_CREATE_DRAFT_OPTIONS = "CreateDraftOptions";
  private CreateDraftOptions createDraftOptions;


  public DraftCreateFromTemplateModel templateId(String templateId) {
    
    this.templateId = templateId;
    return this;
  }

   /**
   * The id of the template.
   * @return templateId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The id of the template.")
  @JsonProperty(JSON_PROPERTY_TEMPLATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTemplateId() {
    return templateId;
  }


  public void setTemplateId(String templateId) {
    this.templateId = templateId;
  }


  public DraftCreateFromTemplateModel envelopeOverrideOptions(EnvelopeOverrideOptions envelopeOverrideOptions) {
    
    this.envelopeOverrideOptions = envelopeOverrideOptions;
    return this;
  }

   /**
   * Get envelopeOverrideOptions
   * @return envelopeOverrideOptions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ENVELOPE_OVERRIDE_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EnvelopeOverrideOptions getEnvelopeOverrideOptions() {
    return envelopeOverrideOptions;
  }


  public void setEnvelopeOverrideOptions(EnvelopeOverrideOptions envelopeOverrideOptions) {
    this.envelopeOverrideOptions = envelopeOverrideOptions;
  }


  public DraftCreateFromTemplateModel createDraftOptions(CreateDraftOptions createDraftOptions) {
    
    this.createDraftOptions = createDraftOptions;
    return this;
  }

   /**
   * Get createDraftOptions
   * @return createDraftOptions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATE_DRAFT_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreateDraftOptions getCreateDraftOptions() {
    return createDraftOptions;
  }


  public void setCreateDraftOptions(CreateDraftOptions createDraftOptions) {
    this.createDraftOptions = createDraftOptions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DraftCreateFromTemplateModel draftCreateFromTemplateModel = (DraftCreateFromTemplateModel) o;
    return Objects.equals(this.templateId, draftCreateFromTemplateModel.templateId) &&
        Objects.equals(this.envelopeOverrideOptions, draftCreateFromTemplateModel.envelopeOverrideOptions) &&
        Objects.equals(this.createDraftOptions, draftCreateFromTemplateModel.createDraftOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateId, envelopeOverrideOptions, createDraftOptions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DraftCreateFromTemplateModel {\n");
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    envelopeOverrideOptions: ").append(toIndentedString(envelopeOverrideOptions)).append("\n");
    sb.append("    createDraftOptions: ").append(toIndentedString(createDraftOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

