/*
 * eSignAnywhere.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package osplus.esignanywhere.v4.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * RadioButton form.
 */
@ApiModel(description = "RadioButton form.")
@JsonPropertyOrder({
  RadioButton.JSON_PROPERTY_VALUE,
  RadioButton.JSON_PROPERTY_RADIO_BUTTON_GROUP_ID,
  RadioButton.JSON_PROPERTY_IS_REQUIRED,
  RadioButton.JSON_PROPERTY_ID,
  RadioButton.JSON_PROPERTY_POSITION_PAGE,
  RadioButton.JSON_PROPERTY_DOC_REF_NUMBER,
  RadioButton.JSON_PROPERTY_POSITION,
  RadioButton.JSON_PROPERTY_SIZE,
  RadioButton.JSON_PROPERTY_IS_HIDDEN,
  RadioButton.JSON_PROPERTY_EXPORT_VALUE,
  RadioButton.JSON_PROPERTY_DESCRIPTION,
  RadioButton.JSON_PROPERTY_KEEP_EXISTING_VALUE,
  RadioButton.JSON_PROPERTY_CUSTOM_ORDER,
  RadioButton.JSON_PROPERTY_DISCRIMINATOR_TYPE
})
@JsonTypeName("RadioButton")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T11:25:21.496783+01:00[Europe/Berlin]")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "DiscriminatorType", visible = true)

public class RadioButton extends Form {
  public static final String JSON_PROPERTY_VALUE = "Value";
  private String value;

  public static final String JSON_PROPERTY_RADIO_BUTTON_GROUP_ID = "RadioButtonGroupId";
  private String radioButtonGroupId;

  public static final String JSON_PROPERTY_IS_REQUIRED = "IsRequired";
  private Boolean isRequired = false;

  public static final String JSON_PROPERTY_ID = "Id";
  private String id;

  public static final String JSON_PROPERTY_POSITION_PAGE = "PositionPage";
  private Integer positionPage = 1;

  public static final String JSON_PROPERTY_DOC_REF_NUMBER = "DocRefNumber";
  private Integer docRefNumber;

  public static final String JSON_PROPERTY_POSITION = "Position";
  private Position position;

  public static final String JSON_PROPERTY_SIZE = "Size";
  private Size size;

  public static final String JSON_PROPERTY_IS_HIDDEN = "IsHidden";
  private Boolean isHidden = false;

  public static final String JSON_PROPERTY_EXPORT_VALUE = "ExportValue";
  private String exportValue;

  public static final String JSON_PROPERTY_DESCRIPTION = "Description";
  private String description;

  public static final String JSON_PROPERTY_KEEP_EXISTING_VALUE = "KeepExistingValue";
  private Boolean keepExistingValue;

  public static final String JSON_PROPERTY_CUSTOM_ORDER = "CustomOrder";
  private Integer customOrder;

  public static final String JSON_PROPERTY_DISCRIMINATOR_TYPE = "DiscriminatorType";
  protected String discriminatorType;


  public RadioButton value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Value of the radiobutton.
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Value of the radiobutton.")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


  public RadioButton radioButtonGroupId(String radioButtonGroupId) {
    
    this.radioButtonGroupId = radioButtonGroupId;
    return this;
  }

   /**
   * Configure if the radiobutton group identifier.
   * @return radioButtonGroupId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Configure if the radiobutton group identifier.")
  @JsonProperty(JSON_PROPERTY_RADIO_BUTTON_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRadioButtonGroupId() {
    return radioButtonGroupId;
  }


  public void setRadioButtonGroupId(String radioButtonGroupId) {
    this.radioButtonGroupId = radioButtonGroupId;
  }


  public RadioButton isRequired(Boolean isRequired) {
    
    this.isRequired = isRequired;
    return this;
  }

   /**
   * Defines if the checkbox is required,
   * @return isRequired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Defines if the checkbox is required,")
  @JsonProperty(JSON_PROPERTY_IS_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsRequired() {
    return isRequired;
  }


  public void setIsRequired(Boolean isRequired) {
    this.isRequired = isRequired;
  }


  public RadioButton id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Identifier for the form.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Identifier for the form.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public RadioButton positionPage(Integer positionPage) {
    
    this.positionPage = positionPage;
    return this;
  }

   /**
   * Page number for the form.
   * @return positionPage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Page number for the form.")
  @JsonProperty(JSON_PROPERTY_POSITION_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPositionPage() {
    return positionPage;
  }


  public void setPositionPage(Integer positionPage) {
    this.positionPage = positionPage;
  }


  public RadioButton docRefNumber(Integer docRefNumber) {
    
    this.docRefNumber = docRefNumber;
    return this;
  }

   /**
   * Document number for the form.
   * @return docRefNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Document number for the form.")
  @JsonProperty(JSON_PROPERTY_DOC_REF_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDocRefNumber() {
    return docRefNumber;
  }


  public void setDocRefNumber(Integer docRefNumber) {
    this.docRefNumber = docRefNumber;
  }


  public RadioButton position(Position position) {
    
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Position getPosition() {
    return position;
  }


  public void setPosition(Position position) {
    this.position = position;
  }


  public RadioButton size(Size size) {
    
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Size getSize() {
    return size;
  }


  public void setSize(Size size) {
    this.size = size;
  }


  public RadioButton isHidden(Boolean isHidden) {
    
    this.isHidden = isHidden;
    return this;
  }

   /**
   * Define if it is hidden.
   * @return isHidden
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Define if it is hidden.")
  @JsonProperty(JSON_PROPERTY_IS_HIDDEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsHidden() {
    return isHidden;
  }


  public void setIsHidden(Boolean isHidden) {
    this.isHidden = isHidden;
  }


  public RadioButton exportValue(String exportValue) {
    
    this.exportValue = exportValue;
    return this;
  }

   /**
   * The export value of the form field.
   * @return exportValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The export value of the form field.")
  @JsonProperty(JSON_PROPERTY_EXPORT_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExportValue() {
    return exportValue;
  }


  public void setExportValue(String exportValue) {
    this.exportValue = exportValue;
  }


  public RadioButton description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Description to provide details about the element.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Description to provide details about the element.")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public RadioButton keepExistingValue(Boolean keepExistingValue) {
    
    this.keepExistingValue = keepExistingValue;
    return this;
  }

   /**
   * If true, form value from Pdf is used.
   * @return keepExistingValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If true, form value from Pdf is used.")
  @JsonProperty(JSON_PROPERTY_KEEP_EXISTING_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getKeepExistingValue() {
    return keepExistingValue;
  }


  public void setKeepExistingValue(Boolean keepExistingValue) {
    this.keepExistingValue = keepExistingValue;
  }


   /**
   * Increasing order number. Can be used for tabbing through the form elements.
   * @return customOrder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Increasing order number. Can be used for tabbing through the form elements.")
  @JsonProperty(JSON_PROPERTY_CUSTOM_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCustomOrder() {
    return customOrder;
  }




  public RadioButton discriminatorType(String discriminatorType) {
    
    this.discriminatorType = discriminatorType;
    return this;
  }

   /**
   * Property for parsing abstract base classes (polymorphism) in auto generated Swagger code.
   * @return discriminatorType
  **/
  @ApiModelProperty(required = true, value = "Property for parsing abstract base classes (polymorphism) in auto generated Swagger code.")
  @JsonProperty(JSON_PROPERTY_DISCRIMINATOR_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDiscriminatorType() {
    return discriminatorType;
  }


  public void setDiscriminatorType(String discriminatorType) {
    this.discriminatorType = discriminatorType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RadioButton radioButton = (RadioButton) o;
    return Objects.equals(this.value, radioButton.value) &&
        Objects.equals(this.radioButtonGroupId, radioButton.radioButtonGroupId) &&
        Objects.equals(this.isRequired, radioButton.isRequired) &&
        Objects.equals(this.id, radioButton.id) &&
        Objects.equals(this.positionPage, radioButton.positionPage) &&
        Objects.equals(this.docRefNumber, radioButton.docRefNumber) &&
        Objects.equals(this.position, radioButton.position) &&
        Objects.equals(this.size, radioButton.size) &&
        Objects.equals(this.isHidden, radioButton.isHidden) &&
        Objects.equals(this.exportValue, radioButton.exportValue) &&
        Objects.equals(this.description, radioButton.description) &&
        Objects.equals(this.keepExistingValue, radioButton.keepExistingValue) &&
        Objects.equals(this.customOrder, radioButton.customOrder) &&
        Objects.equals(this.discriminatorType, radioButton.discriminatorType) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, radioButtonGroupId, isRequired, id, positionPage, docRefNumber, position, size, isHidden, exportValue, description, keepExistingValue, customOrder, discriminatorType, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RadioButton {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    radioButtonGroupId: ").append(toIndentedString(radioButtonGroupId)).append("\n");
    sb.append("    isRequired: ").append(toIndentedString(isRequired)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    positionPage: ").append(toIndentedString(positionPage)).append("\n");
    sb.append("    docRefNumber: ").append(toIndentedString(docRefNumber)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    isHidden: ").append(toIndentedString(isHidden)).append("\n");
    sb.append("    exportValue: ").append(toIndentedString(exportValue)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    keepExistingValue: ").append(toIndentedString(keepExistingValue)).append("\n");
    sb.append("    customOrder: ").append(toIndentedString(customOrder)).append("\n");
    sb.append("    discriminatorType: ").append(toIndentedString(discriminatorType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

