/*
 * eSignAnywhere.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package osplus.esignanywhere.v4.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import io.swagger.annotations.ApiModelProperty;

/**
 * SendEnvelopeDescriptionTemplate
 */
@JsonPropertyOrder({
  SendEnvelopeDescriptionTemplate.JSON_PROPERTY_NAME,
  SendEnvelopeDescriptionTemplate.JSON_PROPERTY_EMAIL_SUBJECT,
  SendEnvelopeDescriptionTemplate.JSON_PROPERTY_EMAIL_BODY,
  SendEnvelopeDescriptionTemplate.JSON_PROPERTY_DISPLAYED_EMAIL_SENDER,
  SendEnvelopeDescriptionTemplate.JSON_PROPERTY_ENABLE_REMINDERS,
  SendEnvelopeDescriptionTemplate.JSON_PROPERTY_FIRST_REMINDER_DAY_AMOUNT,
  SendEnvelopeDescriptionTemplate.JSON_PROPERTY_RECURRENT_REMINDER_DAY_AMOUNT,
  SendEnvelopeDescriptionTemplate.JSON_PROPERTY_BEFORE_EXPIRATION_DAY_AMOUNT,
  SendEnvelopeDescriptionTemplate.JSON_PROPERTY_DAYS_UNTIL_EXPIRE,
  SendEnvelopeDescriptionTemplate.JSON_PROPERTY_CALLBACK_URL,
  SendEnvelopeDescriptionTemplate.JSON_PROPERTY_STATUS_UPDATE_CALLBACK_URL,
  SendEnvelopeDescriptionTemplate.JSON_PROPERTY_WORKSTEP_EVENT_CALLBACK,
  SendEnvelopeDescriptionTemplate.JSON_PROPERTY_STEPS,
  SendEnvelopeDescriptionTemplate.JSON_PROPERTY_ADD_FORM_FIELDS,
  SendEnvelopeDescriptionTemplate.JSON_PROPERTY_META_DATA_XML
})
@JsonTypeName("SendEnvelopeDescriptionTemplate")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-28T10:42:13.714738+01:00[Europe/Berlin]")
public class SendEnvelopeDescriptionTemplate {
  public static final String JSON_PROPERTY_NAME = "Name";
  private String name;

  public static final String JSON_PROPERTY_EMAIL_SUBJECT = "EmailSubject";
  private String emailSubject;

  public static final String JSON_PROPERTY_EMAIL_BODY = "EmailBody";
  private String emailBody;

  public static final String JSON_PROPERTY_DISPLAYED_EMAIL_SENDER = "DisplayedEmailSender";
  private String displayedEmailSender;

  public static final String JSON_PROPERTY_ENABLE_REMINDERS = "EnableReminders";
  private Boolean enableReminders;

  public static final String JSON_PROPERTY_FIRST_REMINDER_DAY_AMOUNT = "FirstReminderDayAmount";
  private Integer firstReminderDayAmount;

  public static final String JSON_PROPERTY_RECURRENT_REMINDER_DAY_AMOUNT = "RecurrentReminderDayAmount";
  private Integer recurrentReminderDayAmount;

  public static final String JSON_PROPERTY_BEFORE_EXPIRATION_DAY_AMOUNT = "BeforeExpirationDayAmount";
  private Integer beforeExpirationDayAmount;

  public static final String JSON_PROPERTY_DAYS_UNTIL_EXPIRE = "DaysUntilExpire";
  private Integer daysUntilExpire = 28;

  public static final String JSON_PROPERTY_CALLBACK_URL = "CallbackUrl";
  private String callbackUrl;

  public static final String JSON_PROPERTY_STATUS_UPDATE_CALLBACK_URL = "StatusUpdateCallbackUrl";
  private String statusUpdateCallbackUrl;

  public static final String JSON_PROPERTY_WORKSTEP_EVENT_CALLBACK = "WorkstepEventCallback";
  private WorkstepEventCallback workstepEventCallback;

  public static final String JSON_PROPERTY_STEPS = "Steps";
  private List<SendEnvelopeStep> steps = null;

  public static final String JSON_PROPERTY_ADD_FORM_FIELDS = "AddFormFields";
  private AddFormFields addFormFields;

  public static final String JSON_PROPERTY_META_DATA_XML = "MetaDataXml";
  private String metaDataXml;


  public SendEnvelopeDescriptionTemplate name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the envelope.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the envelope.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public SendEnvelopeDescriptionTemplate emailSubject(String emailSubject) {
    
    this.emailSubject = emailSubject;
    return this;
  }

   /**
   * The subject of the sent out emails.
   * @return emailSubject
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The subject of the sent out emails.")
  @JsonProperty(JSON_PROPERTY_EMAIL_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmailSubject() {
    return emailSubject;
  }


  public void setEmailSubject(String emailSubject) {
    this.emailSubject = emailSubject;
  }


  public SendEnvelopeDescriptionTemplate emailBody(String emailBody) {
    
    this.emailBody = emailBody;
    return this;
  }

   /**
   * The body of the sent out emails.
   * @return emailBody
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The body of the sent out emails.")
  @JsonProperty(JSON_PROPERTY_EMAIL_BODY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmailBody() {
    return emailBody;
  }


  public void setEmailBody(String emailBody) {
    this.emailBody = emailBody;
  }


  public SendEnvelopeDescriptionTemplate displayedEmailSender(String displayedEmailSender) {
    
    this.displayedEmailSender = displayedEmailSender;
    return this;
  }

   /**
   * The name of the email sender.
   * @return displayedEmailSender
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the email sender.")
  @JsonProperty(JSON_PROPERTY_DISPLAYED_EMAIL_SENDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayedEmailSender() {
    return displayedEmailSender;
  }


  public void setDisplayedEmailSender(String displayedEmailSender) {
    this.displayedEmailSender = displayedEmailSender;
  }


  public SendEnvelopeDescriptionTemplate enableReminders(Boolean enableReminders) {
    
    this.enableReminders = enableReminders;
    return this;
  }

   /**
   * If true, reminders are used.
   * @return enableReminders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If true, reminders are used.")
  @JsonProperty(JSON_PROPERTY_ENABLE_REMINDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnableReminders() {
    return enableReminders;
  }


  public void setEnableReminders(Boolean enableReminders) {
    this.enableReminders = enableReminders;
  }


  public SendEnvelopeDescriptionTemplate firstReminderDayAmount(Integer firstReminderDayAmount) {
    
    this.firstReminderDayAmount = firstReminderDayAmount;
    return this;
  }

   /**
   * Amount of days until the first reminder is sent out.
   * @return firstReminderDayAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Amount of days until the first reminder is sent out.")
  @JsonProperty(JSON_PROPERTY_FIRST_REMINDER_DAY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFirstReminderDayAmount() {
    return firstReminderDayAmount;
  }


  public void setFirstReminderDayAmount(Integer firstReminderDayAmount) {
    this.firstReminderDayAmount = firstReminderDayAmount;
  }


  public SendEnvelopeDescriptionTemplate recurrentReminderDayAmount(Integer recurrentReminderDayAmount) {
    
    this.recurrentReminderDayAmount = recurrentReminderDayAmount;
    return this;
  }

   /**
   * Amount of days until all recurrent reminders are sent out.
   * @return recurrentReminderDayAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Amount of days until all recurrent reminders are sent out.")
  @JsonProperty(JSON_PROPERTY_RECURRENT_REMINDER_DAY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRecurrentReminderDayAmount() {
    return recurrentReminderDayAmount;
  }


  public void setRecurrentReminderDayAmount(Integer recurrentReminderDayAmount) {
    this.recurrentReminderDayAmount = recurrentReminderDayAmount;
  }


  public SendEnvelopeDescriptionTemplate beforeExpirationDayAmount(Integer beforeExpirationDayAmount) {
    
    this.beforeExpirationDayAmount = beforeExpirationDayAmount;
    return this;
  }

   /**
   * Amount of days until a reminder about the expiration is sent out.
   * @return beforeExpirationDayAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Amount of days until a reminder about the expiration is sent out.")
  @JsonProperty(JSON_PROPERTY_BEFORE_EXPIRATION_DAY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBeforeExpirationDayAmount() {
    return beforeExpirationDayAmount;
  }


  public void setBeforeExpirationDayAmount(Integer beforeExpirationDayAmount) {
    this.beforeExpirationDayAmount = beforeExpirationDayAmount;
  }


  public SendEnvelopeDescriptionTemplate daysUntilExpire(Integer daysUntilExpire) {
    
    this.daysUntilExpire = daysUntilExpire;
    return this;
  }

   /**
   * Amount of days until the envelope expires.
   * @return daysUntilExpire
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Amount of days until the envelope expires.")
  @JsonProperty(JSON_PROPERTY_DAYS_UNTIL_EXPIRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDaysUntilExpire() {
    return daysUntilExpire;
  }


  public void setDaysUntilExpire(Integer daysUntilExpire) {
    this.daysUntilExpire = daysUntilExpire;
  }


  public SendEnvelopeDescriptionTemplate callbackUrl(String callbackUrl) {
    
    this.callbackUrl = callbackUrl;
    return this;
  }

   /**
   * The callback url of the envelope.
   * @return callbackUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The callback url of the envelope.")
  @JsonProperty(JSON_PROPERTY_CALLBACK_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCallbackUrl() {
    return callbackUrl;
  }


  public void setCallbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }


  public SendEnvelopeDescriptionTemplate statusUpdateCallbackUrl(String statusUpdateCallbackUrl) {
    
    this.statusUpdateCallbackUrl = statusUpdateCallbackUrl;
    return this;
  }

   /**
   * The callback url of status changes for the envelope.
   * @return statusUpdateCallbackUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The callback url of status changes for the envelope.")
  @JsonProperty(JSON_PROPERTY_STATUS_UPDATE_CALLBACK_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatusUpdateCallbackUrl() {
    return statusUpdateCallbackUrl;
  }


  public void setStatusUpdateCallbackUrl(String statusUpdateCallbackUrl) {
    this.statusUpdateCallbackUrl = statusUpdateCallbackUrl;
  }


  public SendEnvelopeDescriptionTemplate workstepEventCallback(WorkstepEventCallback workstepEventCallback) {
    
    this.workstepEventCallback = workstepEventCallback;
    return this;
  }

   /**
   * Get workstepEventCallback
   * @return workstepEventCallback
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WORKSTEP_EVENT_CALLBACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public WorkstepEventCallback getWorkstepEventCallback() {
    return workstepEventCallback;
  }


  public void setWorkstepEventCallback(WorkstepEventCallback workstepEventCallback) {
    this.workstepEventCallback = workstepEventCallback;
  }


  public SendEnvelopeDescriptionTemplate steps(List<SendEnvelopeStep> steps) {
    
    this.steps = steps;
    return this;
  }

  public SendEnvelopeDescriptionTemplate addStepsItem(SendEnvelopeStep stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<SendEnvelopeStep>();
    }
    this.steps.add(stepsItem);
    return this;
  }

   /**
   * The steps for the envelope.
   * @return steps
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The steps for the envelope.")
  @JsonProperty(JSON_PROPERTY_STEPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SendEnvelopeStep> getSteps() {
    return steps;
  }


  public void setSteps(List<SendEnvelopeStep> steps) {
    this.steps = steps;
  }


  public SendEnvelopeDescriptionTemplate addFormFields(AddFormFields addFormFields) {
    
    this.addFormFields = addFormFields;
    return this;
  }

   /**
   * Get addFormFields
   * @return addFormFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADD_FORM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AddFormFields getAddFormFields() {
    return addFormFields;
  }


  public void setAddFormFields(AddFormFields addFormFields) {
    this.addFormFields = addFormFields;
  }


  public SendEnvelopeDescriptionTemplate metaDataXml(String metaDataXml) {
    
    this.metaDataXml = metaDataXml;
    return this;
  }

   /**
   * Get metaDataXml
   * @return metaDataXml
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_META_DATA_XML)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMetaDataXml() {
    return metaDataXml;
  }


  public void setMetaDataXml(String metaDataXml) {
    this.metaDataXml = metaDataXml;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendEnvelopeDescriptionTemplate sendEnvelopeDescriptionTemplate = (SendEnvelopeDescriptionTemplate) o;
    return Objects.equals(this.name, sendEnvelopeDescriptionTemplate.name) &&
        Objects.equals(this.emailSubject, sendEnvelopeDescriptionTemplate.emailSubject) &&
        Objects.equals(this.emailBody, sendEnvelopeDescriptionTemplate.emailBody) &&
        Objects.equals(this.displayedEmailSender, sendEnvelopeDescriptionTemplate.displayedEmailSender) &&
        Objects.equals(this.enableReminders, sendEnvelopeDescriptionTemplate.enableReminders) &&
        Objects.equals(this.firstReminderDayAmount, sendEnvelopeDescriptionTemplate.firstReminderDayAmount) &&
        Objects.equals(this.recurrentReminderDayAmount, sendEnvelopeDescriptionTemplate.recurrentReminderDayAmount) &&
        Objects.equals(this.beforeExpirationDayAmount, sendEnvelopeDescriptionTemplate.beforeExpirationDayAmount) &&
        Objects.equals(this.daysUntilExpire, sendEnvelopeDescriptionTemplate.daysUntilExpire) &&
        Objects.equals(this.callbackUrl, sendEnvelopeDescriptionTemplate.callbackUrl) &&
        Objects.equals(this.statusUpdateCallbackUrl, sendEnvelopeDescriptionTemplate.statusUpdateCallbackUrl) &&
        Objects.equals(this.workstepEventCallback, sendEnvelopeDescriptionTemplate.workstepEventCallback) &&
        Objects.equals(this.steps, sendEnvelopeDescriptionTemplate.steps) &&
        Objects.equals(this.addFormFields, sendEnvelopeDescriptionTemplate.addFormFields) &&
        Objects.equals(this.metaDataXml, sendEnvelopeDescriptionTemplate.metaDataXml);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, emailSubject, emailBody, displayedEmailSender, enableReminders, firstReminderDayAmount, recurrentReminderDayAmount, beforeExpirationDayAmount, daysUntilExpire, callbackUrl, statusUpdateCallbackUrl, workstepEventCallback, steps, addFormFields, metaDataXml);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendEnvelopeDescriptionTemplate {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    emailSubject: ").append(toIndentedString(emailSubject)).append("\n");
    sb.append("    emailBody: ").append(toIndentedString(emailBody)).append("\n");
    sb.append("    displayedEmailSender: ").append(toIndentedString(displayedEmailSender)).append("\n");
    sb.append("    enableReminders: ").append(toIndentedString(enableReminders)).append("\n");
    sb.append("    firstReminderDayAmount: ").append(toIndentedString(firstReminderDayAmount)).append("\n");
    sb.append("    recurrentReminderDayAmount: ").append(toIndentedString(recurrentReminderDayAmount)).append("\n");
    sb.append("    beforeExpirationDayAmount: ").append(toIndentedString(beforeExpirationDayAmount)).append("\n");
    sb.append("    daysUntilExpire: ").append(toIndentedString(daysUntilExpire)).append("\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    statusUpdateCallbackUrl: ").append(toIndentedString(statusUpdateCallbackUrl)).append("\n");
    sb.append("    workstepEventCallback: ").append(toIndentedString(workstepEventCallback)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    addFormFields: ").append(toIndentedString(addFormFields)).append("\n");
    sb.append("    metaDataXml: ").append(toIndentedString(metaDataXml)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

