/*
 * eSignAnywhere.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package osplus.esignanywhere.v4.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Options for Post Messaging in Iframes.
 */
@ApiModel(description = "Options for Post Messaging in Iframes.")
@JsonPropertyOrder({
  VisibleAreaOptions.JSON_PROPERTY_ALLOWED_DOMAIN,
  VisibleAreaOptions.JSON_PROPERTY_ENABLED
})
@JsonTypeName("VisibleAreaOptions")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-28T10:42:13.714738+01:00[Europe/Berlin]")
public class VisibleAreaOptions {
  public static final String JSON_PROPERTY_ALLOWED_DOMAIN = "AllowedDomain";
  private String allowedDomain;

  public static final String JSON_PROPERTY_ENABLED = "Enabled";
  private Boolean enabled;


  public VisibleAreaOptions allowedDomain(String allowedDomain) {
    
    this.allowedDomain = allowedDomain;
    return this;
  }

   /**
   * Allowed domains for post messaging.  E.g. \&quot;esignanywhere.com\&quot;
   * @return allowedDomain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Allowed domains for post messaging.  E.g. \"esignanywhere.com\"")
  @JsonProperty(JSON_PROPERTY_ALLOWED_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAllowedDomain() {
    return allowedDomain;
  }


  public void setAllowedDomain(String allowedDomain) {
    this.allowedDomain = allowedDomain;
  }


  public VisibleAreaOptions enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * Defines if post messaging should be enabled.  Default is false.
   * @return enabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Defines if post messaging should be enabled.  Default is false.")
  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VisibleAreaOptions visibleAreaOptions = (VisibleAreaOptions) o;
    return Objects.equals(this.allowedDomain, visibleAreaOptions.allowedDomain) &&
        Objects.equals(this.enabled, visibleAreaOptions.enabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowedDomain, enabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VisibleAreaOptions {\n");
    sb.append("    allowedDomain: ").append(toIndentedString(allowedDomain)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

