/*
 * eSignAnywhere.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package osplus.esignanywhere.v4.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The workstep configuration used to create the workstep.
 */
@ApiModel(description = "The workstep configuration used to create the workstep.")
@JsonPropertyOrder({
  WorkstepConfiguration.JSON_PROPERTY_WORKSTEP_LABEL,
  WorkstepConfiguration.JSON_PROPERTY_SMALL_TEXT_ZOOM_FACTOR_PERCENT,
  WorkstepConfiguration.JSON_PROPERTY_FINISH_ACTION,
  WorkstepConfiguration.JSON_PROPERTY_INTRO_TEXTS,
  WorkstepConfiguration.JSON_PROPERTY_RECEIVER_INFORMATION,
  WorkstepConfiguration.JSON_PROPERTY_SENDER_INFORMATION,
  WorkstepConfiguration.JSON_PROPERTY_TRANSACTION_CODE_CONFIGURATIONS,
  WorkstepConfiguration.JSON_PROPERTY_SIGNATURE_CONFIGURATIONS,
  WorkstepConfiguration.JSON_PROPERTY_VIEWER_PREFERENCES,
  WorkstepConfiguration.JSON_PROPERTY_RESOURCE_URIS,
  WorkstepConfiguration.JSON_PROPERTY_AUTHENTICATION_METHODS,
  WorkstepConfiguration.JSON_PROPERTY_ADDITIONAL_CLIENT_WORKSTEP_INFORMATION,
  WorkstepConfiguration.JSON_PROPERTY_AUDITING_TOOLS_CONFIGURATION,
  WorkstepConfiguration.JSON_PROPERTY_POLICY
})
@JsonTypeName("WorkstepConfiguration")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-13T11:25:21.496783+01:00[Europe/Berlin]")
public class WorkstepConfiguration {
  public static final String JSON_PROPERTY_WORKSTEP_LABEL = "WorkstepLabel";
  private String workstepLabel;

  public static final String JSON_PROPERTY_SMALL_TEXT_ZOOM_FACTOR_PERCENT = "SmallTextZoomFactorPercent";
  private Integer smallTextZoomFactorPercent = 100;

  public static final String JSON_PROPERTY_FINISH_ACTION = "FinishAction";
  private FinishAction finishAction;

  public static final String JSON_PROPERTY_INTRO_TEXTS = "IntroTexts";
  private IntroTexts introTexts;

  public static final String JSON_PROPERTY_RECEIVER_INFORMATION = "ReceiverInformation";
  private ReceiverInformation receiverInformation;

  public static final String JSON_PROPERTY_SENDER_INFORMATION = "SenderInformation";
  private SenderInformation senderInformation;

  public static final String JSON_PROPERTY_TRANSACTION_CODE_CONFIGURATIONS = "TransactionCodeConfigurations";
  private List<TransactionCodeConfiguration> transactionCodeConfigurations = null;

  public static final String JSON_PROPERTY_SIGNATURE_CONFIGURATIONS = "SignatureConfigurations";
  private List<SignatureConfiguration> signatureConfigurations = null;

  public static final String JSON_PROPERTY_VIEWER_PREFERENCES = "ViewerPreferences";
  private ViewerPreferences viewerPreferences;

  public static final String JSON_PROPERTY_RESOURCE_URIS = "ResourceUris";
  private ResourceUris resourceUris;

  public static final String JSON_PROPERTY_AUTHENTICATION_METHODS = "AuthenticationMethods";
  private AuthenticationMethods authenticationMethods;

  public static final String JSON_PROPERTY_ADDITIONAL_CLIENT_WORKSTEP_INFORMATION = "AdditionalClientWorkstepInformation";
  private String additionalClientWorkstepInformation;

  public static final String JSON_PROPERTY_AUDITING_TOOLS_CONFIGURATION = "AuditingToolsConfiguration";
  private AuditingToolsConfiguration auditingToolsConfiguration;

  public static final String JSON_PROPERTY_POLICY = "Policy";
  private Policy policy;


  public WorkstepConfiguration workstepLabel(String workstepLabel) {
    
    this.workstepLabel = workstepLabel;
    return this;
  }

   /**
   * A label for this workstep.
   * @return workstepLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A label for this workstep.")
  @JsonProperty(JSON_PROPERTY_WORKSTEP_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWorkstepLabel() {
    return workstepLabel;
  }


  public void setWorkstepLabel(String workstepLabel) {
    this.workstepLabel = workstepLabel;
  }


  public WorkstepConfiguration smallTextZoomFactorPercent(Integer smallTextZoomFactorPercent) {
    
    this.smallTextZoomFactorPercent = smallTextZoomFactorPercent;
    return this;
  }

   /**
   * Defines a image generation correction factor. If for example this document contains very small text, which might not be readable with the standard image resolution of the client, this factor can be used to tell the client to get a higher resolution.
   * @return smallTextZoomFactorPercent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Defines a image generation correction factor. If for example this document contains very small text, which might not be readable with the standard image resolution of the client, this factor can be used to tell the client to get a higher resolution.")
  @JsonProperty(JSON_PROPERTY_SMALL_TEXT_ZOOM_FACTOR_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSmallTextZoomFactorPercent() {
    return smallTextZoomFactorPercent;
  }


  public void setSmallTextZoomFactorPercent(Integer smallTextZoomFactorPercent) {
    this.smallTextZoomFactorPercent = smallTextZoomFactorPercent;
  }


  public WorkstepConfiguration finishAction(FinishAction finishAction) {
    
    this.finishAction = finishAction;
    return this;
  }

   /**
   * Get finishAction
   * @return finishAction
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FINISH_ACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FinishAction getFinishAction() {
    return finishAction;
  }


  public void setFinishAction(FinishAction finishAction) {
    this.finishAction = finishAction;
  }


  public WorkstepConfiguration introTexts(IntroTexts introTexts) {
    
    this.introTexts = introTexts;
    return this;
  }

   /**
   * Get introTexts
   * @return introTexts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INTRO_TEXTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public IntroTexts getIntroTexts() {
    return introTexts;
  }


  public void setIntroTexts(IntroTexts introTexts) {
    this.introTexts = introTexts;
  }


  public WorkstepConfiguration receiverInformation(ReceiverInformation receiverInformation) {
    
    this.receiverInformation = receiverInformation;
    return this;
  }

   /**
   * Get receiverInformation
   * @return receiverInformation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RECEIVER_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ReceiverInformation getReceiverInformation() {
    return receiverInformation;
  }


  public void setReceiverInformation(ReceiverInformation receiverInformation) {
    this.receiverInformation = receiverInformation;
  }


  public WorkstepConfiguration senderInformation(SenderInformation senderInformation) {
    
    this.senderInformation = senderInformation;
    return this;
  }

   /**
   * Get senderInformation
   * @return senderInformation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SENDER_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SenderInformation getSenderInformation() {
    return senderInformation;
  }


  public void setSenderInformation(SenderInformation senderInformation) {
    this.senderInformation = senderInformation;
  }


  public WorkstepConfiguration transactionCodeConfigurations(List<TransactionCodeConfiguration> transactionCodeConfigurations) {
    
    this.transactionCodeConfigurations = transactionCodeConfigurations;
    return this;
  }

  public WorkstepConfiguration addTransactionCodeConfigurationsItem(TransactionCodeConfiguration transactionCodeConfigurationsItem) {
    if (this.transactionCodeConfigurations == null) {
      this.transactionCodeConfigurations = new ArrayList<TransactionCodeConfiguration>();
    }
    this.transactionCodeConfigurations.add(transactionCodeConfigurationsItem);
    return this;
  }

   /**
   * Collection of TransactionCodeConfigurations
   * @return transactionCodeConfigurations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Collection of TransactionCodeConfigurations")
  @JsonProperty(JSON_PROPERTY_TRANSACTION_CODE_CONFIGURATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TransactionCodeConfiguration> getTransactionCodeConfigurations() {
    return transactionCodeConfigurations;
  }


  public void setTransactionCodeConfigurations(List<TransactionCodeConfiguration> transactionCodeConfigurations) {
    this.transactionCodeConfigurations = transactionCodeConfigurations;
  }


  public WorkstepConfiguration signatureConfigurations(List<SignatureConfiguration> signatureConfigurations) {
    
    this.signatureConfigurations = signatureConfigurations;
    return this;
  }

  public WorkstepConfiguration addSignatureConfigurationsItem(SignatureConfiguration signatureConfigurationsItem) {
    if (this.signatureConfigurations == null) {
      this.signatureConfigurations = new ArrayList<SignatureConfiguration>();
    }
    this.signatureConfigurations.add(signatureConfigurationsItem);
    return this;
  }

   /**
   * Collection of SignatureConfigurations
   * @return signatureConfigurations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Collection of SignatureConfigurations")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_CONFIGURATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SignatureConfiguration> getSignatureConfigurations() {
    return signatureConfigurations;
  }


  public void setSignatureConfigurations(List<SignatureConfiguration> signatureConfigurations) {
    this.signatureConfigurations = signatureConfigurations;
  }


  public WorkstepConfiguration viewerPreferences(ViewerPreferences viewerPreferences) {
    
    this.viewerPreferences = viewerPreferences;
    return this;
  }

   /**
   * Get viewerPreferences
   * @return viewerPreferences
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VIEWER_PREFERENCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ViewerPreferences getViewerPreferences() {
    return viewerPreferences;
  }


  public void setViewerPreferences(ViewerPreferences viewerPreferences) {
    this.viewerPreferences = viewerPreferences;
  }


  public WorkstepConfiguration resourceUris(ResourceUris resourceUris) {
    
    this.resourceUris = resourceUris;
    return this;
  }

   /**
   * Get resourceUris
   * @return resourceUris
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RESOURCE_URIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResourceUris getResourceUris() {
    return resourceUris;
  }


  public void setResourceUris(ResourceUris resourceUris) {
    this.resourceUris = resourceUris;
  }


  public WorkstepConfiguration authenticationMethods(AuthenticationMethods authenticationMethods) {
    
    this.authenticationMethods = authenticationMethods;
    return this;
  }

   /**
   * Get authenticationMethods
   * @return authenticationMethods
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUTHENTICATION_METHODS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuthenticationMethods getAuthenticationMethods() {
    return authenticationMethods;
  }


  public void setAuthenticationMethods(AuthenticationMethods authenticationMethods) {
    this.authenticationMethods = authenticationMethods;
  }


   /**
   * Additional client workstep information.
   * @return additionalClientWorkstepInformation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional client workstep information.")
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_CLIENT_WORKSTEP_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdditionalClientWorkstepInformation() {
    return additionalClientWorkstepInformation;
  }




  public WorkstepConfiguration auditingToolsConfiguration(AuditingToolsConfiguration auditingToolsConfiguration) {
    
    this.auditingToolsConfiguration = auditingToolsConfiguration;
    return this;
  }

   /**
   * Get auditingToolsConfiguration
   * @return auditingToolsConfiguration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUDITING_TOOLS_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditingToolsConfiguration getAuditingToolsConfiguration() {
    return auditingToolsConfiguration;
  }


  public void setAuditingToolsConfiguration(AuditingToolsConfiguration auditingToolsConfiguration) {
    this.auditingToolsConfiguration = auditingToolsConfiguration;
  }


  public WorkstepConfiguration policy(Policy policy) {
    
    this.policy = policy;
    return this;
  }

   /**
   * Get policy
   * @return policy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_POLICY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Policy getPolicy() {
    return policy;
  }


  public void setPolicy(Policy policy) {
    this.policy = policy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkstepConfiguration workstepConfiguration = (WorkstepConfiguration) o;
    return Objects.equals(this.workstepLabel, workstepConfiguration.workstepLabel) &&
        Objects.equals(this.smallTextZoomFactorPercent, workstepConfiguration.smallTextZoomFactorPercent) &&
        Objects.equals(this.finishAction, workstepConfiguration.finishAction) &&
        Objects.equals(this.introTexts, workstepConfiguration.introTexts) &&
        Objects.equals(this.receiverInformation, workstepConfiguration.receiverInformation) &&
        Objects.equals(this.senderInformation, workstepConfiguration.senderInformation) &&
        Objects.equals(this.transactionCodeConfigurations, workstepConfiguration.transactionCodeConfigurations) &&
        Objects.equals(this.signatureConfigurations, workstepConfiguration.signatureConfigurations) &&
        Objects.equals(this.viewerPreferences, workstepConfiguration.viewerPreferences) &&
        Objects.equals(this.resourceUris, workstepConfiguration.resourceUris) &&
        Objects.equals(this.authenticationMethods, workstepConfiguration.authenticationMethods) &&
        Objects.equals(this.additionalClientWorkstepInformation, workstepConfiguration.additionalClientWorkstepInformation) &&
        Objects.equals(this.auditingToolsConfiguration, workstepConfiguration.auditingToolsConfiguration) &&
        Objects.equals(this.policy, workstepConfiguration.policy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workstepLabel, smallTextZoomFactorPercent, finishAction, introTexts, receiverInformation, senderInformation, transactionCodeConfigurations, signatureConfigurations, viewerPreferences, resourceUris, authenticationMethods, additionalClientWorkstepInformation, auditingToolsConfiguration, policy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkstepConfiguration {\n");
    sb.append("    workstepLabel: ").append(toIndentedString(workstepLabel)).append("\n");
    sb.append("    smallTextZoomFactorPercent: ").append(toIndentedString(smallTextZoomFactorPercent)).append("\n");
    sb.append("    finishAction: ").append(toIndentedString(finishAction)).append("\n");
    sb.append("    introTexts: ").append(toIndentedString(introTexts)).append("\n");
    sb.append("    receiverInformation: ").append(toIndentedString(receiverInformation)).append("\n");
    sb.append("    senderInformation: ").append(toIndentedString(senderInformation)).append("\n");
    sb.append("    transactionCodeConfigurations: ").append(toIndentedString(transactionCodeConfigurations)).append("\n");
    sb.append("    signatureConfigurations: ").append(toIndentedString(signatureConfigurations)).append("\n");
    sb.append("    viewerPreferences: ").append(toIndentedString(viewerPreferences)).append("\n");
    sb.append("    resourceUris: ").append(toIndentedString(resourceUris)).append("\n");
    sb.append("    authenticationMethods: ").append(toIndentedString(authenticationMethods)).append("\n");
    sb.append("    additionalClientWorkstepInformation: ").append(toIndentedString(additionalClientWorkstepInformation)).append("\n");
    sb.append("    auditingToolsConfiguration: ").append(toIndentedString(auditingToolsConfiguration)).append("\n");
    sb.append("    policy: ").append(toIndentedString(policy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

